export const ROUTES = {
	Splash: "Splash",
	OnboardScreen: "OnboardScreen",
	Login: "Login",
	HomeStack: "HomeStack",
	Bottom_Tab: "Bottom_Tab",
	Home: "Home",
	StartScan: "StartScan",
	TakeAttendance: "TakeAttendance",
	Record: "Record",
	AttendanceDetails: "AttendanceDetails",
	BarcodeScreen: "BarcodeScreen",
	Confirmation: "Confirmation",
	Report: "Report",
	Profile: "Profile",
	ProfileDetails: "ProfileDetails",
};
